version: "3.8"

services:
    user-service:
        image: user-service
        container_name: user-service
        build: .
        ports:
            - 4000:3000
        networks:
            - microservice
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - DIRECT_URL=${DIRECT_URL}
            - JWT_SECRET=${JWT_SECRET}
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run dev

networks:
    microservice:
        name: microservice
        driver: bridge
